name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "264391bc8e5e649f15364f5acc0a0e516d5f7eef4f439c599edf4c256b639f9b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.7"
