name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f33544a70ccfc38b68bc9a3b112967430fdd64d3e7484cded884fcf8c59be0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
