name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e8c45d0c59d245c1d3d11b563d96ca5189cc277f53ecc7cf98c761ba8fa2056"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
