name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23eb9e24cd4582a71f9688cc64d4f288c091203627418f33aa63c17b89ad184f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
