name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ccd2c9ed007ef68a3e70d5d33f14bae293c69cf4fa652bb69c345148352b27a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
