name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88c044b0899b736e69dd99b95809e8f5eb11066fcdacf31501ff30da4f6547b8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
