name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5b848dcdb86e1a117419f060d3aa98af77201de594f8dc2db7c14fc353eccb6"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
