name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "118dfda95fd0a30ef8840c70940348e4b978711ad82db8cfe827451e1e84eaca"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
