name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5083ff75044ae2bc0d3bae8b4aafabf7ae7b00b190647a8e7f4598b1cf270ee3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
