name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58daf145d3dff4c976946ec3a1aa7915d7d016bde5efc3928b2e0d5cbf5baf84"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
