name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f1d1e53e502b8228a2f6e837262f150a3c93f84ab595fc762fec499868d252f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
