name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1478d097738966fb42566f4eb95400f28aac6d79371304483ee804bca609958"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
