name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dccf6a8e85671a7b2c1506662585a6a7f4a9d8c2c62ea797b2ea755ef74c8df"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
