name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8cb18066207ed328cad8fc7cc66968ac3787d4ff4a8a54990b48490dcb8f987"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
