name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8cf6a60af70dfc2e7e712f58d35f772e1c396b9891e651988cc4c75890ff93"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
