name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0abe6723ba325c39f3bc89408e0f565a7b31bd5e97c2a2c475f003dc6754561"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
