name = "twigModpack"
author = "Twig"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f01a2c677dd897df30d9c39b25aa5b624cbf82b565245941316c09d7f0a2bfa0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
